[build]
  # https://answers.netlify.com/t/build-canceled-due-to-no-content-change-when-using-submodule/25445/2
  ignore = "false"

[build.environment]
  PYTHON_VERSION = "3.8"
  HUGO_VERSION = "0.104.1"

[[plugins]]
  package = "netlify-plugin-checklinks"
