[build]
  # https://answers.netlify.com/t/build-canceled-due-to-no-content-change-when-using-submodule/25445/2
  ignore = "false"

[build.environment]
  PYTHON_VERSION = "3.8" # netlify currently only support 2.7 and 3.8
  HUGO_VERSION = "0.112.3"

[[plugins]]
  package = "netlify-plugin-checklinks"
